### ISSUE TITLE
SyntaxError when Running nightwatch.conf.BASIC.js File

### ISSUE THREAD

**Issue by S-Voss** [dwyl/learn-nightwatch#48]
I am able to get as far as Step 7 on running nightwatch on my own project, however, when I go to run the nightwatch.conf.BASIC.js file it throws a SyntaxError: Unexpected token <
at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

What exactly do I do to fix this? I do not know where to go from here or what that means. 

Thank you in advance for helping me.

**Comment by naazy** [comment]
@S-Voss how did you resolve this? Thanks
