### ISSUE TITLE
Complete Beginners Tutorial - npm test - produces error:  Cannot find module 'env2'

### ISSUE THREAD

**Issue by hellfireSteve** [dwyl/learn-nightwatch#87]
Trying to follow this tutorial, but it fails on step 3: npm test.

response:

ERROR Error: Cannot find module 'env2'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\learn-nightwatch\nightwatch.conf.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)****

It would help if the tutorial stuff actually worked!

**Comment by nelsonic** [comment]
@hellfireSteve _thank you_ for opening this issue.
It appears from your debug log output that you are running Microsoft Windows.
You may need to follow additional instructions on the http://nightwatchjs.org site if you haven't already.
The _first_ line of your debug output indicates that you have not installed the `env2` module. 
please attempt to do this: `npm install env2` and then re-try running `npm test`
thanks.
